Remove Newtonsoft.Json APIs from System.Net.Http.Formatting
mono/reference-assemblies pull request #7
Opened 2018-05-18 17:37 UTC by radical

- Also, remove 3 methods that referenced Newtonsoft.Json types

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=23668

2018-05-18 18:06 UTC, akoeplinger requested changes
You'll need to regenerate the .dll which is checked in. Run `make -C mono CSC="mono <path to mono>/external/roslyn-binaries/Microsoft.Net.Compilers/Microsoft.Net.Compilers.2.1.0/tools/csc.exe"`

2018-05-18 18:32 UTC, radical commented
@akoeplinger generated the assembly.

2018-05-18 18:35 UTC, akoeplinger approved these changes

2018-05-18 18:35 UTC, merged

2018-05-29 09:21 UTC, marek-safar commented
@radical please bump the submodule dependency in Mono too